# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0002_auto_20170526_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='pass_word',
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=40, verbose_name='城市名称'),
        ),
        migrations.AlterField(
            model_name='machinegroup',
            name='group_name',
            field=models.CharField(max_length=40, verbose_name='组名称'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='application',
            field=models.CharField(max_length=600, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='cache',
            field=models.CharField(max_length=12, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='cpu',
            field=models.CharField(max_length=4, verbose_name='cpu'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='hard_disk',
            field=models.CharField(max_length=20, verbose_name='磁盘'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='machine_ip',
            field=models.CharField(max_length=15, unique=True, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='machine_model',
            field=models.CharField(max_length=40, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='machine_os',
            field=models.CharField(max_length=40, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='status',
            field=models.CharField(choices=[('on', '正常'), ('off', '损坏')], max_length=8, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='machineroom',
            name='machine_room_name',
            field=models.CharField(max_length=40, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='record',
            name='go_time',
            field=models.CharField(max_length=20, null=True, verbose_name='巡检时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='humidity',
            field=models.IntegerField(null=True, verbose_name='湿度'),
        ),
        migrations.AlterField(
            model_name='record',
            name='mark',
            field=models.CharField(max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='record',
            name='net',
            field=models.CharField(max_length=10, verbose_name='网络设备'),
        ),
        migrations.AlterField(
            model_name='record',
            name='server',
            field=models.CharField(max_length=100, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='record',
            name='temperature',
            field=models.IntegerField(null=True, verbose_name='温度'),
        ),
        migrations.AlterField(
            model_name='record',
            name='trouble',
            field=models.CharField(max_length=200, verbose_name='故障处理'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hys_operation.UserJob', verbose_name='职位id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_mobile',
            field=models.BigIntegerField(verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='department',
            field=models.CharField(max_length=80, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='job_name',
            field=models.CharField(max_length=40, verbose_name='职位'),
        ),
    ]
