# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0003_auto_20170526_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hys_operation.UserJob', verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hys_operation.MachineGroup', verbose_name='部门'),
        ),
    ]
