# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-27 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0004_auto_20170526_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='go_time',
            field=models.DateTimeField(null=True, verbose_name='巡检时间'),
        ),
    ]
