# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0007_auto_20170527_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinfo',
            name='status',
            field=models.CharField(choices=[('正常', '正常'), ('损坏', '损坏')], max_length=8, verbose_name='状态'),
        ),
    ]
