# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0008_auto_20170531_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='machine_room_id',
            field=models.ForeignKey(db_column='machine_room_id', on_delete=django.db.models.deletion.CASCADE, to='hys_operation.MachineRoom', verbose_name='所属机房'),
        ),
    ]
