# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0010_auto_20170602_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id', verbose_name='用户id')),
                ('group_id', models.IntegerField(db_column='group_id', verbose_name='属组id')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'verbose_name': '人员属组关系表',
                'verbose_name_plural': '人员属组关系表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPaperStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目归属')),
                ('to_mail', models.CharField(max_length=100, verbose_name='接收邮箱')),
                ('data_selected', models.CharField(max_length=1000, verbose_name='数据选项')),
                ('proposer', models.CharField(max_length=100, verbose_name='申请人')),
                ('frequency', models.CharField(max_length=400, verbose_name='频率')),
                ('commit_date', models.DateField(null=True, verbose_name='申请时间')),
                ('sql', models.TextField(max_length=10000, verbose_name='sql语句')),
                ('paper_num', models.CharField(max_length=10, verbose_name='备案号')),
            ],
            options={
                'db_table': 'data_paper_store',
                'verbose_name': '数据单备案表',
                'verbose_name_plural': '数据单备案表',
            },
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False, 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='hard_disk',
            field=models.CharField(max_length=200, verbose_name='磁盘'),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='os_mark',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='备注'),
        ),
    ]
