# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0011_auto_20170818_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapaperstore',
            name='is_sure',
            field=models.BooleanField(default=False, verbose_name='是否已确认'),
        ),
    ]
