# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0012_datapaperstore_is_sure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapaperstore',
            name='to_mail',
            field=models.EmailField(max_length=254, verbose_name='接收邮箱'),
        ),
    ]
