# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0013_auto_20170818_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapaperstore',
            name='data_selected',
            field=models.TextField(max_length=1000, verbose_name='数据选项'),
        ),
    ]
