# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0014_auto_20170818_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapaperstore',
            name='paper_num',
            field=models.CharField(max_length=20, verbose_name='备案号'),
        ),
    ]
