# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0015_auto_20170821_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapaperstore',
            name='end_date',
            field=models.DateField(auto_now=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='datapaperstore',
            name='mark',
            field=models.TextField(max_length=10000, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='datapaperstore',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='datapaperstore',
            name='commit_date',
            field=models.DateField(auto_now_add=True, verbose_name='申请时间'),
        ),
    ]
