# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0016_auto_20170821_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapaperstore',
            name='commit_date',
            field=models.DateField(auto_now=True, verbose_name='申请时间'),
        ),
    ]
