# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0019_auto_20170821_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapaperstore',
            name='paper_num',
            field=models.CharField(max_length=32, verbose_name='备案号'),
        ),
        migrations.AlterField(
            model_name='datapaperstore',
            name='sql',
            field=models.TextField(max_length=100000, verbose_name='sql语句'),
        ),
    ]
