# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-09 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0022_datapaperstore_is_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type_name', models.CharField(max_length=200, null=True, verbose_name='配件类型名称')),
            ],
            options={
                'db_table': 'part_type',
                'verbose_name': '服务器配件类型表',
                'verbose_name_plural': '服务器配件类型表',
            },
        ),
    ]
