# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-09 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0023_parttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='server_ip_id',
            field=models.ForeignKey(db_column='server_ip_id', default=8, on_delete=django.db.models.deletion.CASCADE, to='hys_operation.MachineInfo', verbose_name='服务器'),
        ),
    ]
