# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-09 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0024_record_server_ip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='trouble_type_id',
            field=models.ForeignKey(db_column='trouble_type_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='hys_operation.PartType', verbose_name='故障类型'),
        ),
    ]
