# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-09 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0026_auto_20180109_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='server',
            field=models.CharField(max_length=200, verbose_name='故障内容'),
        ),
    ]
