# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0027_auto_20180109_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoDicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dic_name', models.CharField(max_length=200, verbose_name='字典名称')),
                ('seq', models.IntegerField(verbose_name='顺序号')),
            ],
            options={
                'db_table': 'co_dic_data',
                'verbose_name_plural': '字典表',
                'verbose_name': '字典表',
            },
        ),
        migrations.CreateModel(
            name='CoDicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, verbose_name='字典类型')),
            ],
            options={
                'db_table': 'co_dic_type',
                'verbose_name_plural': '字典类型表',
                'verbose_name': '字典类型表',
            },
        ),
        migrations.AddField(
            model_name='codicdata',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hys_operation.CoDicType', verbose_name='类型id'),
        ),
    ]
