# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0028_auto_20180109_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codicdata',
            name='type_id',
        ),
        migrations.AddField(
            model_name='codicdata',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hys_operation.CoDicType', verbose_name='字典类型'),
            preserve_default=False,
        ),
    ]
