# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0029_auto_20180110_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportDba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(null=True, verbose_name='创建时间')),
                ('db_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_id', to='hys_operation.CoDicData', verbose_name='DB服务器')),
            ],
        ),
    ]
