# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0030_dailyreportdba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreportdba',
            options={'verbose_name': 'DBA日志', 'verbose_name_plural': 'DBA日志'},
        ),
        migrations.AlterModelTable(
            name='dailyreportdba',
            table='daily_report_dba',
        ),
    ]
