# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0031_auto_20180110_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdba',
            name='db_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hys_operation.CoDicData', verbose_name='DB服务器'),
        ),
    ]
