# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0032_auto_20180110_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportdba',
            name='db_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='username', to='hys_operation.CoDicData', verbose_name='DB用户名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreportdba',
            name='db_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='hys_operation.CoDicData', verbose_name='DB服务器'),
        ),
    ]
