# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0033_auto_20180110_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='db_server',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='db_user',
        ),
        migrations.DeleteModel(
            name='DailyReportDba',
        ),
    ]
