# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0035_dailyreportdba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdba',
            name='request',
            field=models.TextField(max_length=10000, verbose_name='需求'),
        ),
    ]
