# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0037_auto_20180110_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codicdata',
            name='type',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='db_server',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='db_user',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='proposer',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='request_type',
        ),
        migrations.AddField(
            model_name='codictype',
            name='type_code',
            field=models.CharField(default=1, max_length=2, verbose_name='字典编码'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CoDicData',
        ),
        migrations.DeleteModel(
            name='DailyReportDba',
        ),
    ]
