# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0039_codicdata_dailyreportdba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='proposer',
        ),
        migrations.AddField(
            model_name='dailyreportdba',
            name='de_proposer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='hys_operation.CoDicData', verbose_name='申请人(开发)'),
            preserve_default=False,
        ),
    ]
