# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0041_dailyreportdba_fde_proposer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdba',
            name='remark',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='dailyreportdba',
            name='scripts',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='脚本'),
        ),
    ]
