# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-10 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0042_auto_20180110_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='codicdata',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='上级id'),
        ),
    ]
