# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-15 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0043_codicdata_parent_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': False, 'verbose_name': 'CO--人员属组关系表', 'verbose_name_plural': 'CO--人员属组关系表'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'CO--城市分布表', 'verbose_name_plural': 'CO--城市分布表'},
        ),
        migrations.AlterModelOptions(
            name='codicdata',
            options={'verbose_name': 'CO--字典表', 'verbose_name_plural': 'CO--字典表'},
        ),
        migrations.AlterModelOptions(
            name='codictype',
            options={'verbose_name': 'CO--字典类型表', 'verbose_name_plural': 'CO--字典类型表'},
        ),
        migrations.AlterModelOptions(
            name='dailyreportdba',
            options={'verbose_name': 'AA--日志(DBA)', 'verbose_name_plural': 'AA--日志(DBA)'},
        ),
        migrations.AlterModelOptions(
            name='datapaperstore',
            options={'verbose_name': 'AA--数据单备案表', 'verbose_name_plural': 'AA--数据单备案表'},
        ),
        migrations.AlterModelOptions(
            name='machinegroup',
            options={'verbose_name': 'CO--主机属组表', 'verbose_name_plural': 'CO--主机属组表'},
        ),
        migrations.AlterModelOptions(
            name='machineinfo',
            options={'verbose_name': 'AA--主机信息表', 'verbose_name_plural': 'AA--主机信息表'},
        ),
        migrations.AlterModelOptions(
            name='machineroom',
            options={'verbose_name': 'CO--机房信息表', 'verbose_name_plural': 'CO--机房信息表'},
        ),
        migrations.AlterModelOptions(
            name='parttype',
            options={'verbose_name': 'CO--服务器配件类型表', 'verbose_name_plural': 'CO--服务器配件类型表'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'AA--巡检记录表', 'verbose_name_plural': 'AA--巡检记录表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False, 'verbose_name': 'AA--用户表', 'verbose_name_plural': 'AA--用户表'},
        ),
        migrations.AlterModelOptions(
            name='userjob',
            options={'verbose_name': 'CO--职位表', 'verbose_name_plural': 'CO--职位表'},
        ),
        migrations.AlterUniqueTogether(
            name='codicdata',
            unique_together=set([('dic_name', 'type')]),
        ),
    ]
