# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-15 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0044_auto_20180115_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codicdata',
            unique_together=set([('dic_name', 'type', 'parent_id')]),
        ),
    ]
