# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-16 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0045_auto_20180115_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinfo',
            name='machine_ip',
            field=models.CharField(max_length=100, unique=True, verbose_name='ip地址'),
        ),
    ]
