# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0048_auto_20180413_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='db_server',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='db_user',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='de_proposer',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='fde_proposer',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='request',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='request_type',
        ),
    ]
