# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0049_auto_20180413_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codictype',
            options={'managed': True, 'verbose_name': 'CO--字典类型表', 'verbose_name_plural': 'CO--字典类型表'},
        ),
        migrations.RemoveField(
            model_name='machineinfo',
            name='band_width',
        ),
    ]
