# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0050_auto_20180413_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codictype',
            options={'verbose_name': 'CO--字典类型表', 'verbose_name_plural': 'CO--字典类型表'},
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='band_width',
            field=models.ForeignKey(db_column='band_width', default=228, on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth', to='hys_operation.CoDicData', verbose_name='带宽'),
        ),
    ]
