# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0051_auto_20180413_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=200, unique=True, verbose_name='域名')),
                ('project_name', models.CharField(max_length=2000, verbose_name='项目名称')),
                ('create_date', models.DateTimeField(verbose_name='创建时间')),
                ('de_charge', models.ManyToManyField(related_name='kf', to='hys_operation.UserInfo', verbose_name='开发负责人')),
                ('fde_charge', models.ManyToManyField(related_name='nb', to='hys_operation.UserInfo', verbose_name='内部负责人')),
                ('project_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fz', to='hys_operation.UserInfo', verbose_name='项目负责人')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gs', to='hys_operation.ProjectType', verbose_name='项目归属')),
            ],
            options={
                'verbose_name_plural': 'AA--项目表',
                'verbose_name': 'AA--项目表',
                'db_table': 'project',
            },
        ),
    ]
