# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0052_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'AA--用户表', 'verbose_name_plural': 'AA--用户表'},
        ),
    ]
