# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0053_auto_20180413_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mgr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hys_operation.UserInfo', verbose_name='上级'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='privilege',
            field=models.IntegerField(choices=[(0, '普通权限'), (1, '高级权限')], db_column='privilege', default=0, verbose_name='显示权限'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pro_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hys_operation.ProjectType', verbose_name='项目归属'),
        ),
    ]
