# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0054_auto_20180413_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportdba',
            name='create_date',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='dailyreportdba',
            name='db_server',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='hys_operation.CoDicData', verbose_name='DB服务器'),
        ),
        migrations.AddField(
            model_name='dailyreportdba',
            name='db_user',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.CASCADE, related_name='username', to='hys_operation.CoDicData', verbose_name='DB用户名'),
        ),
        migrations.AddField(
            model_name='dailyreportdba',
            name='de_proposer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='hys_operation.CoDicData', verbose_name='申请人(开发)'),
        ),
        migrations.AddField(
            model_name='dailyreportdba',
            name='fde_proposer',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, related_name='fpr', to='hys_operation.CoDicData', verbose_name='申请人(非开发)'),
        ),
        migrations.AddField(
            model_name='dailyreportdba',
            name='operator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='oper', to='hys_operation.CoDicData', verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='dailyreportdba',
            name='request',
            field=models.TextField(max_length=10000, null=True, verbose_name='需求'),
        ),
        migrations.AddField(
            model_name='dailyreportdba',
            name='request_type',
            field=models.ForeignKey(default=89, on_delete=django.db.models.deletion.CASCADE, related_name='re', to='hys_operation.CoDicData', verbose_name='需求类型'),
        ),
    ]
