# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0055_auto_20180413_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='create_date',
        ),
    ]
