# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0056_remove_dailyreportdba_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='db_server',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='db_user',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='de_proposer',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='fde_proposer',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='dailyreportdba',
            name='request_type',
        ),
        migrations.DeleteModel(
            name='DailyReportDba',
        ),
    ]
