# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0057_auto_20180413_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportDba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(null=True, verbose_name='创建时间')),
                ('request', models.TextField(max_length=10000, null=True, verbose_name='需求')),
                ('scripts', models.TextField(blank=True, max_length=10000, null=True, verbose_name='脚本')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('remark', models.TextField(blank=True, max_length=10000, null=True, verbose_name='备注')),
                ('db_server', models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, related_name='server', to='hys_operation.CoDicData', verbose_name='DB服务器')),
                ('db_user', models.ForeignKey(default=120, on_delete=django.db.models.deletion.CASCADE, related_name='username', to='hys_operation.CoDicData', verbose_name='DB用户名')),
                ('de_proposer', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='hys_operation.CoDicData', verbose_name='申请人(开发)')),
                ('fde_proposer', models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, related_name='fpr', to='hys_operation.CoDicData', verbose_name='申请人(非开发)')),
                ('operator', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='oper', to='hys_operation.CoDicData', verbose_name='操作人')),
                ('request_type', models.ForeignKey(default=89, on_delete=django.db.models.deletion.CASCADE, related_name='re', to='hys_operation.CoDicData', verbose_name='需求类型')),
            ],
            options={
                'verbose_name': 'AA--日志(DBA)',
                'db_table': 'daily_report_dba',
                'verbose_name_plural': 'AA--日志(DBA)',
            },
        ),
    ]
