# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-13 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0058_dailyreportdba'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportOsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(null=True, verbose_name='创建时间')),
                ('scripts', models.TextField(blank=True, max_length=10000, null=True, verbose_name='操作')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('remark', models.TextField(blank=True, max_length=10000, null=True, verbose_name='备注')),
                ('db_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_server', to='hys_operation.MachineInfo', verbose_name='DB服务器')),
                ('de_proposer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='de', to='hys_operation.CoDicData', verbose_name='申请人(开发)')),
                ('fde_proposer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fde', to='hys_operation.CoDicData', verbose_name='申请人(非开发)')),
                ('operations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op', to='hys_operation.CoDicData', verbose_name='操作类型')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opt', to='hys_operation.CoDicData', verbose_name='操作人')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hys_operation.Project', verbose_name='项目')),
                ('web_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_server', to='hys_operation.MachineInfo', verbose_name='WEB服务器')),
            ],
            options={
                'db_table': 'daily_report_osa',
                'verbose_name_plural': 'AA--日志(OSA)',
                'verbose_name': 'AA--日志(OSA)',
            },
        ),
    ]
