# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0059_dailyreportosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportosa',
            name='machine_room_id',
            field=models.ForeignKey(db_column='machine_room_id', default=3, on_delete=django.db.models.deletion.CASCADE, to='hys_operation.MachineRoom', verbose_name='所属机房'),
        ),
    ]
