# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0062_auto_20180416_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportosa',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hys_operation.Project', verbose_name='项目'),
        ),
    ]
