# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0063_auto_20180416_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='act_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act', to='hys_operation.CoDicData', verbose_name='巡检人'),
        ),
    ]
