# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0065_auto_20180417_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinfo',
            name='machine_os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_os', to='hys_operation.CoDicData', verbose_name='操作系统'),
        ),
    ]
