# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hys_operation', '0066_auto_20180417_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codicdata',
            name='seq',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='顺序号'),
        ),
    ]
